// Optional real-browser regression test. Set PLAYWRIGHT_MODULE and BROWSER_EXECUTABLE.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});
  try {
    const page=await browser.newPage({viewport:{width:1200,height:1000}});
    const errors=[]; page.on('pageerror',error=>errors.push(error.message));
    await page.route('http://panel.test/**',async route=>{
      const name=new URL(route.request().url()).pathname.slice(1);
      if(name.endsWith('.js')) return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'custom_components/tuya_ir_bridge/www',name),'utf8')});
      return route.fulfill({contentType:'text/html',body:`<html><style>body{margin:0;--primary-text-color:#e1e1e1;--secondary-text-color:#aaa;--card-background-color:#1c1c1c;--primary-background-color:#111;--secondary-background-color:#282828;--primary-color:#03a9f4;--input-fill-color:#222;--input-ink-color:#555}</style><zigbee-ir-ready-panel></zigbee-ir-ready-panel><script type="module">
      import '/manager.js';
      window.devices=[{id:'ac',name:'Bedroom AC',device_type:'climate',protocol:'ELECTRA_AC',topic:'zigbee2mqtt/Bedroom/set/ir_code_to_send',transport:'zosung',model:-1,min_temp:16,max_temp:32,temp_step:1,hvac_options:{SwingV:'Auto'}},{id:'tv',name:'Legacy TV',device_type:'remote',protocol:'nec',address:18,topic:'zigbee2mqtt/TV/set/ir_code_to_send',commands:{power:32}}];
      window.requests=[];window.failLearning=true;
      window.hass={themes:{darkMode:true},states:{'sensor.living_room_temperature':{entity_id:'sensor.living_room_temperature',attributes:{friendly_name:'Living Room Temperature',device_class:'temperature',unit_of_measurement:'°C'}},'sensor.living_room_humidity':{entity_id:'sensor.living_room_humidity',attributes:{friendly_name:'Living Room Humidity',device_class:'humidity',unit_of_measurement:'%'}},'sensor.total_energy':{entity_id:'sensor.total_energy',attributes:{friendly_name:'Total Energy',device_class:'energy',unit_of_measurement:'kWh'}},'binary_sensor.ac_power':{entity_id:'binary_sensor.ac_power',attributes:{friendly_name:'AC Power',device_class:'power'}},'binary_sensor.front_door':{entity_id:'binary_sensor.front_door',attributes:{friendly_name:'Front Door',device_class:'door'}}},callWS:async message=>{
        window.requests.push(message);
        if(message.type.endsWith('/list'))return structuredClone(window.devices);
        if(message.type.endsWith('/catalogue'))return {climate:['DAIKIN','ELECTRA_AC','GREE'],send:[{name:'NEC'},{name:'SONY'}]};
        if(message.type.endsWith('/update')){const saved={...message.device,id:message.device_id};window.devices=window.devices.map(d=>d.id===saved.id?saved:d);return saved;}
        if(message.type.endsWith('/delete')){window.devices=window.devices.filter(d=>d.id!==message.device_id);return {deleted:message.device_id};}
        if(message.action==='learn_start'){if(window.failLearning){window.failLearning=false;throw {code:'invalid_action',message:'MQTT subscription failed'};}return {session:'learn-one'};}
        if(message.action==='learn_status')return {status:'learned',code:'B4gjlBEwApoG',command:{Protocol:'NEC',Bits:32,Data:'0x20DF10EF'}};
        if(message.type.endsWith('/action'))return {};
        throw Error('Unexpected request');
      }};
      document.querySelector('zigbee-ir-ready-panel').hass=window.hass;
      </script></html>`});
    });
    await page.goto('http://panel.test/');
    assert.equal(await page.evaluate(()=>customCards.some(card=>card.type==='zigbee-ir-ready-remote-card')),true);
    await page.getByRole('button',{name:'Edit Bedroom AC'}).click();
    assert.equal(await page.locator('#name').inputValue(),'Bedroom AC');
    assert.equal(await page.locator('#protocol').inputValue(),'ELECTRA_AC');
    assert.equal(await page.locator('#device_type').isDisabled(),true);
    assert.equal(await page.getByRole('tab',{name:'Behavior',exact:true}).count(),1);
    assert.equal(await page.getByRole('tab',{name:'Advanced',exact:true}).count(),0);
    assert.equal(await page.locator('[name="temperature_sensor"] option',{hasText:'Living Room Temperature'}).count(),1);
    assert.equal(await page.locator('[name="temperature_sensor"] option',{hasText:'Living Room Humidity'}).count(),0);
    assert.equal(await page.locator('[name="temperature_sensor"] option',{hasText:'Total Energy'}).count(),0);
    assert.equal(await page.locator('[name="humidity_sensor"] option',{hasText:'Living Room Humidity'}).count(),1);
    assert.equal(await page.locator('[name="humidity_sensor"] option',{hasText:'Living Room Temperature'}).count(),0);
    assert.equal(await page.locator('[name="power_sensor"] option',{hasText:'AC Power'}).count(),1);
    assert.equal(await page.locator('[name="power_sensor"] option',{hasText:'Front Door'}).count(),0);
    await page.locator('[name="availability_topic"]').fill('zigbee2mqtt/Bedroom/availability');
    const colors=await page.locator('#protocol option').first().evaluate(option=>({color:getComputedStyle(option).color,background:getComputedStyle(option).backgroundColor,scheme:getComputedStyle(option).colorScheme}));
    assert.equal(colors.color,'rgb(225, 225, 225)');
    assert.equal(colors.background,'rgb(28, 28, 28)');
    assert.equal(colors.scheme,'dark');
    await page.locator('#protocol').evaluate(select=>select.size=3);
    fs.mkdirSync(path.join(root,'.build'),{recursive:true});
    await page.screenshot({path:path.join(root,'.build/panel-dark-edit.png'),fullPage:true});
    await page.locator('#protocol').evaluate(select=>select.size=1);
    await page.locator('#name').fill('Bedroom AC Updated');
    await page.getByRole('tab',{name:'Capabilities',exact:true}).click();
    await page.locator('#max_temp').fill('30');
    await page.locator('[data-choice="hvac_modes"][value="heat"]').uncheck();
    await page.locator('[data-choice="swing_modes"][value="vertical"]').check();
    await page.locator('[name="initial_target_temp"]').fill('23');
    await page.screenshot({path:path.join(root,'.build/panel-ac-capabilities.png'),fullPage:true});
    await page.getByRole('tab',{name:'Behavior',exact:true}).click();
    await page.locator('[data-choice="feature_switches"][value="Turbo"]').check();
    await page.locator('[name="keep_mode_on_power_on"]').check();
    await page.screenshot({path:path.join(root,'.build/panel-ac-behavior.png'),fullPage:true});
    await page.getByRole('button',{name:'Save Changes',exact:true}).click();
    await page.getByRole('status').filter({hasText:'Changes saved'}).waitFor();
    let updates=await page.evaluate(()=>requests.filter(r=>r.type.endsWith('/update')));
    assert.equal(updates.length,1); assert.equal(updates[0].device_id,'ac');
    assert.equal(updates[0].device.max_temp,30);
    assert.equal(updates[0].device.hvac_modes.includes('heat'),false);
    assert.deepEqual(updates[0].device.swing_modes,['vertical']);
    assert.deepEqual(updates[0].device.feature_switches,['Turbo']);
    assert.equal(updates[0].device.initial_target_temp,23);
    assert.equal(updates[0].device.keep_mode_on_power_on,true);
    assert.equal(updates[0].device.availability_topic,'zigbee2mqtt/Bedroom/availability');
    assert.equal(await page.evaluate(()=>devices.length),2);
    await page.getByRole('button',{name:'Edit Legacy TV'}).click();
    await page.getByRole('tab',{name:'Connection',exact:true}).click();
    assert.equal(await page.locator('#address').inputValue(),'18');
    assert.equal(await page.locator('#transport').inputValue(),'base64');
    await page.getByRole('tab',{name:'Sources',exact:true}).click();
    const sourceCycle=page.locator('.command-row').filter({has:page.locator('[data-command="source_cycle"]')});
    assert.equal(await sourceCycle.locator('.command-name').textContent(),'Cycle Source');
    assert.equal(await sourceCycle.getByRole('button',{name:'Learn',exact:true}).count(),1);
    assert.equal(await sourceCycle.getByRole('button',{name:'Test',exact:true}).count(),1);
    assert.match(await page.locator('[data-pane="sources"] .help').textContent(),/one input per press/);
    await page.getByRole('button',{name:'Save Changes',exact:true}).click();
    await page.getByRole('status').filter({hasText:'Changes saved'}).waitFor();
    updates=await page.evaluate(()=>requests.filter(r=>r.type.endsWith('/update')));
    assert.equal(updates[1].device.address,18);
    await page.getByRole('tab',{name:'Power & Volume',exact:true}).click();
    const power=page.locator('.command-row').filter({has:page.locator('[data-command="power"]')});
    assert.equal(await power.locator('[data-learn]').evaluate(button=>getComputedStyle(button).backgroundColor),'rgb(255, 152, 0)');
    assert.equal(await power.locator('[data-test]').evaluate(button=>getComputedStyle(button).backgroundColor),'rgb(46, 125, 50)');
    assert.equal(await power.locator('ha-icon').count(),2);
    await power.getByRole('button',{name:'Learn',exact:true}).click();
    const learning=page.getByRole('dialog',{name:'Learn IR command'});
    await learning.getByRole('status').filter({hasText:'MQTT subscription failed'}).waitFor();
    await page.waitForTimeout(700);
    assert.equal(await learning.isVisible(),true);
    await learning.getByRole('button',{name:'Retry',exact:true}).click();
    await learning.getByRole('status').filter({hasText:'Success — command learned'}).waitFor();
    assert.equal(await learning.isVisible(),true);
    await learning.waitFor({state:'detached',timeout:4000});
    assert.equal(await power.locator('.command-code').inputValue(),'0x20DF10EF');
    const commandLayout=await power.evaluate(row=>[...row.querySelectorAll('.command-code,button')].map(node=>Math.round(node.getBoundingClientRect().top)));
    assert.equal(new Set(commandLayout).size,1);
    await power.getByRole('button',{name:'Test',exact:true}).click();
    await page.getByRole('status').filter({hasText:'Command sent'}).waitFor();
    await page.getByRole('button',{name:'Save Changes',exact:true}).click();
    await page.getByRole('status').filter({hasText:'Changes saved'}).waitFor();
    assert.deepEqual(await page.evaluate(()=>devices.find(d=>d.id==='tv').commands.power),{Protocol:'NEC',Bits:32,Data:'0x20DF10EF'});
    await page.screenshot({path:path.join(root,'.build/panel-commands.png'),fullPage:true});
    await page.evaluate(()=>{hass.themes.darkMode=false;document.body.style.setProperty('--primary-text-color','#212121');document.body.style.setProperty('--card-background-color','#fff');document.querySelector('zigbee-ir-ready-panel').hass=hass;});
    assert.equal(await page.locator('#protocol').evaluate(el=>getComputedStyle(el).colorScheme),'light');
    await page.getByRole('button',{name:'Delete Device',exact:true}).click();
    await page.getByRole('button',{name:'Cancel',exact:true}).click();
    assert.equal(await page.evaluate(()=>devices.length),2);
    await page.getByRole('button',{name:'Delete Device',exact:true}).click();
    await page.getByRole('button',{name:'Delete permanently',exact:true}).click();
    await page.getByRole('status').filter({hasText:'Device deleted'}).waitFor();
    assert.equal(await page.evaluate(()=>devices.length),1);
    assert.equal(await page.getByRole('button',{name:'Edit Legacy TV'}).count(),0);
    await page.evaluate(async()=>{document.body.style.setProperty('--primary-text-color','#e1e1e1');document.body.style.setProperty('--card-background-color','#1c1c1c');const card=document.createElement('zigbee-ir-ready-remote-card');document.body.replaceChildren(card);window.remoteCalls=[];card.setConfig({entity:'remote.tv',title:'Living Room TV'});card.hass={states:{'remote.tv':{state:'on',attributes:{friendly_name:'Living Room TV',zigbee_ir_device_id:'tv',configured_commands:['power','volume_up','up','ok','digit_1','source_cycle','play','pause','play_pause','stop','next','previous','rewind','fast_forward'],source_list:[]}}},callService:async(...args)=>remoteCalls.push(args)};});
    assert.equal(await page.evaluate(()=>customCards.some(card=>card.type==='zigbee-ir-ready-remote-card')),true);
    await page.locator('[data-cmd="power"]').first().click();
    assert.equal(await page.evaluate(()=>remoteCalls[0][2].command),'power');
    await page.locator('[data-cmd="source_cycle"]').first().click();
    assert.equal(await page.evaluate(()=>remoteCalls[1][2].command),'source_cycle');
    const playbackIcons={play:'mdi:play',pause:'mdi:pause',play_pause:'mdi:play-pause',stop:'mdi:stop',next:'mdi:skip-next',previous:'mdi:skip-previous',rewind:'mdi:rewind',fast_forward:'mdi:fast-forward'};
    for(const [command,icon] of Object.entries(playbackIcons)){
      const button=page.locator(`[data-cmd="${command}"]`).first();
      assert.equal(await button.locator('ha-icon').getAttribute('icon'),icon);
      assert.equal(await button.locator('.b-lbl').count(),0);
    }
    const playbackLayout=await page.evaluate(()=>{
      const box=command=>document.querySelector(`zigbee-ir-ready-remote-card`).shadowRoot.querySelector(`[data-cmd="${command}"]`).getBoundingClientRect();
      const play=box('play'),previous=box('previous'),next=box('next');
      const trackRow=previous.closest('.playback-track-row').getBoundingClientRect();
      return {playTop:Math.round(play.top),previousTop:Math.round(previous.top),nextTop:Math.round(next.top),playWidth:Math.round(play.width),previousWidth:Math.round(previous.width),nextWidth:Math.round(next.width),trackWidth:Math.round(trackRow.width)};
    });
    assert.equal(playbackLayout.previousTop,playbackLayout.nextTop);
    assert.notEqual(playbackLayout.playTop,playbackLayout.previousTop);
    assert.ok(playbackLayout.previousWidth>playbackLayout.playWidth);
    assert.ok(playbackLayout.nextWidth>playbackLayout.playWidth);
    assert.ok(playbackLayout.trackWidth<=324);
    await page.screenshot({path:path.join(root,'.build/panel-remotes.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('Browser: dark/light colors, edit loading, stable update ID, and legacy address retention passed');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
